# -*- coding: utf-8 -*-
"""Nufi_Language_Model_Text_Generation_NGram-ChatGPT.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1YktZ5GMXdVY3VK9x4gguK_JoHIWx-aWL
"""

import os
import sys
import requests

# Removed Colab-specific drive mount and inline pip install.
# This script will run locally. Requirements are in requirements.txt.

# REFERENCE: https://www.analyticsvidhya.com/blog/2019/08/comprehensive-guide-language-model-nlp-python-code/?


# code courtesy of https://nlpforhackers.io/language-models/
import pandas as pd

from nltk.corpus import reuters
from nltk import bigrams, trigrams, ngrams

from collections import Counter, defaultdict
import nltk

def clean_text(x, punct = [".",",",";",":","!","?"]):
  for i in punct:
    x = x.replace(i,"")
    x = x.strip()
    x = " ".join(x.split())
  return x

"""# Getting the data"""

# Download a small test corpus if not present
file_url = "https://raw.githubusercontent.com/tchamna/recommender/main/corpus_vocabulaire_nufi_test.txt"
local_fname = "corpus_vocabulaire_nufi_test.txt"
if not os.path.exists(local_fname):
    try:
        r = requests.get(file_url, timeout=30)
        r.raise_for_status()
        with open(local_fname, "wb") as f:
            f.write(r.content)
        print(f"Downloaded {local_fname}")
    except Exception as e:
        print(f"Could not download {file_url}: {e}")

def from_many_documents_to_text(folder_path, output_file="combined_output_test.txt"):
    try:
        from docx import Document
    except Exception:
        print("python-docx is not installed; skipping .docx combination.")
        return

    if not os.path.isdir(folder_path):
        print(f"Folder {folder_path} does not exist; skipping .docx combination.")
        return

    with open(output_file, 'w', encoding='utf-8') as output:
        for filename in os.listdir(folder_path):
            if filename.endswith('.docx'):
                doc = Document(os.path.join(folder_path, filename))
                output.write('\n'.join([paragraph.text for paragraph in doc.paragraphs]) + '\n')

    print(f"Documents combined and successfully saved here:{output_file}")

# Use Google Drive corpus folder first
base_dir = os.getcwd()
folder_path = r"G:\My Drive\Data_Science\DataSets\Nufi\Nufi_Documents\Nufi_Only"
output_file = "main_file1.txt"

from_many_documents_to_text(folder_path, output_file)

import os

# folder_path = '/path/to/folder'  # Specify the folder path where the text files are located
# output_file = '/path/to/output.txt'  # Specify the path and name for the output file

def combine_text_files(folder_path, output_file, encoding='utf-8-sig'):
    if not os.path.isdir(folder_path):
        print(f"Folder {folder_path} does not exist; skipping combine_text_files.")
        return

    with open(output_file, 'a', encoding=encoding) as output:
        for file_name in os.listdir(folder_path):
            if file_name.endswith('.txt'):
                file_path = os.path.join(folder_path, file_name)
                with open(file_path, 'r', encoding=encoding, errors='ignore') as file:
                    output.write(file.read() + '\n')


directory = folder_path
output_file = "main_file2.txt"

combine_text_files(directory, output_file)


directory = base_dir
output_file = "main_file.txt"

combine_text_files(directory, output_file)

# path = "/content/Corpus Nufi.txt"
# with open(path) as f:
#   all_nufi1 = f.readlines()


all_nufi = []
if os.path.exists("corpus_vocabulaire_nufi_test.txt"):
    with open("corpus_vocabulaire_nufi_test.txt", encoding='utf-8', errors='ignore') as f:
        all_nufi = f.readlines()
elif os.path.exists("main_file.txt"):
    with open("main_file.txt", encoding='utf-8', errors='ignore') as f:
        all_nufi = f.readlines()
else:
    print("No corpus files found; proceeding with empty corpus list.")

path_data = os.path.join(base_dir, "data", "Nufi")
file_name1 = "conversation_base_nufi.txt"
file_name2 = "phrasebooknufi.txt"

conv_base = []
phrasebooknufi = []
if os.path.isdir(path_data):
    if os.path.exists(os.path.join(path_data, file_name1)):
        with open(os.path.join(path_data, file_name1), encoding='utf-8', errors='ignore') as f:
            conv_base = f.readlines()
    if os.path.exists(os.path.join(path_data, file_name2)):
        with open(os.path.join(path_data, file_name2), encoding='utf-8', errors='ignore') as f:
            phrasebooknufi = f.readlines()
else:
    print(f"Data folder {path_data} not found; skipping additional files.")

corpus_nufi1 = phrasebooknufi + conv_base
corpus_nufi1;

# pd.DataFrame(corpus_nufi1).to_csv("Corpus_Nufi.csv",encoding="utf 8 - sig")

# with open(r"corpus_vocabulaire_nufi_test.txt") as f:
#   nufi_ = f.readlines()
# nufi_[0:5]
corpus_nufi2 = all_nufi+corpus_nufi1
corpus_nufi_all = list(set(corpus_nufi2))

nufi_clean = [clean_text(i.lower()) for i in corpus_nufi_all]

pd.DataFrame(corpus_nufi_all).to_csv("all_nufi_sentence.csv", encoding="utf 8 - sig")

nufi_tokens = [i.split() for i in nufi_clean]
nufi_tokens[0:5]



"""# Build Ngram Model

## Next Word Prediction
"""

import pickle
from collections import defaultdict
from nltk import ngrams
import nltk

# Download necessary NLTK resources
nltk.download('reuters');
nltk.download('punkt');

path_model_ngrams = os.path.join(base_dir, "data", "Nufi", "Nufi_language_model_ngram.pickle")
# Ensure directory for model exists
os.makedirs(os.path.dirname(path_model_ngrams), exist_ok=True)


def create_defaultdict():
    return defaultdict(int)

# Create a placeholder for the model
model_ngram = defaultdict(create_defaultdict)

def model_generation_ngram(nufi_clean, nufi_tokens, initial_text="Ngɑ̌ yú' mɑ́ á", ngram_size=5):
    starting_seq_tuple = tuple(initial_text.split(" "))

    # Count frequency of co-occurrence
    for sentence in nufi_tokens:
        for gram in ngrams(sentence, ngram_size, pad_right=True, pad_left=True):
            w_tuple = tuple(gram[:-1])
            next_word = gram[-1]
            model_ngram[w_tuple][next_word] += 1

    # Transform counts to probabilities
    for w_tuple in model_ngram:
        total_count = float(sum(model_ngram[w_tuple].values()))
        for next_word in model_ngram[w_tuple]:
            model_ngram[w_tuple][next_word] /= total_count

    starting_seq_str = " ".join(starting_seq_tuple)
    next_word = dict(model_ngram[starting_seq_tuple])
    next_word_list = sorted(next_word, key=next_word.get, reverse=True)
    next_word_prob = [{i: round(next_word[i], 5)} for i in next_word_list]
    phrase_list_containing_starting_seq = [i for i in nufi_clean if starting_seq_str in i]

    with open(path_model_ngrams, 'wb') as file:
        pickle.dump(model_ngram, file)

    return next_word_list, next_word_prob, phrase_list_containing_starting_seq

text = "ngɑ̌ mɑ́"
# text = "ngɑ̌ yú' mɑ́"
# text = "à kɑ̀'"

n = len(text.split(" ")) + 1 # Set the desired value of n (n-gram order)

next_word_list, next_word_prob, phrase_list_containing_starting_seq = model_generation_ngram(nufi_clean, nufi_tokens, text, n)

print("next_word_list:\n", next_word_list)
print()
print("next_word_prob:\n", next_word_prob)
print()
print("Phrases Containing Starting Sequence:\n", phrase_list_containing_starting_seq)

n

"""## Text generation"""

import random

def text_generation_ngram(text="ngɑ̌ yú' mɑ́", model=model_ngram, n=4):
    text = " ".join(text.lower().split())
    text = text.split(" ")
    text_ = text[:]

    if len(model[tuple(text_[-n+1:])].keys()) == 0:
        return f"{' '.join(text_)} not in corpus"

    sentence_finished = False

    while not sentence_finished:
        r = random.random()
        accumulator = .0
        tup = tuple(text_[-n+1:])
        for word in model[tuple(text_[-n+1:])].keys():
            accumulator += model[tuple(text_[-n+1:])][word]
            if accumulator >= r:
                text_.append(word)
                break

        if text_[-n+2:] == [None] * (n - 2):
            sentence_finished = True

    text_generated = ' '.join([t for t in text_ if t])

    if text_generated in nufi_clean:
        return ("Original", text_generated)
    else:
        return ("Text Generated", text_generated)

text = "ǎ lén mɑ́"

text = "à kɑ̀'"

n = len(text.split(" ")) + 1 # Set the desired value of n (n-gram order)

# tuple_text = tuple(text)
res = text_generation_ngram(text,n=n)

res





text = "ǎ lén mɑ́"
# text = "ǎ ghè' tɑ̀"
# text = "kōsī ā lɑ́"
text = "zī ā lɑ́"

text = " ".join(text.split(" ")[:n-1])

text = "sī sīē"
text = "à kɑ̀'"

n = len(text.split(" ")) + 1 # Set the desired value of n (n-gram order)

# text = "ǒ sì cáh wěn mbhì mɑ̄ njàm nnó'nɑ̄h"
# text = "ngɑ̌ lén"

sent_generated = []
c = 0
while True:

  c +=1

  if c==7500:
    break

  # text = ["ǎ", "yá'"]
  # text = ["ngɑ̌", "yú'"]

  aa = text_generation_ngram(text,n=n)

  if aa[0] == "Text Generated":
    sent_generated.append(aa[1])

list(set(sent_generated))





"""#CLASS"""

class NufiTextGenerator:

  import pickle
  from collections import defaultdict
  from nltk import ngrams
  import nltk

  # Download necessary NLTK resources
  nltk.download('reuters');
  nltk.download('punkt');

  def __init__(self,path_model,ngrams_windows):
     self.path_model_ngrams = path_model
     self.ngrams_windows = ngrams_windows
     self.defaultdict = defaultdict

  # path_model_ngrams = "/content/drive/MyDrive/Data_Science/DataSets/Nufi/Nufi_language_model_ngram.pickle"

  def clean_text(self,x, punct = [".",",",";",":","!","?"]):
    for i in punct:
      x = x.replace(i,"")
      x = x.strip()
      x = " ".join(x.split())
    return x

  def create_defaultdict(self):
      return defaultdict(int)

  # Create a placeholder for the model
  model_ngram = defaultdict(int)

  def model_predictiction_ngram(self,nufi_clean, nufi_tokens, initial_text="Ngɑ̌ yú' mɑ́ á"):
      starting_seq_tuple = tuple(initial_text.split(" "))

      # Count frequency of co-occurrence
      for sentence in nufi_tokens:
          for gram in ngrams(sentence, self.ngrams_windows, pad_right=True, pad_left=True):
              w_tuple = tuple(gram[:-1])
              next_word = gram[-1]
              model_ngram[w_tuple][next_word] += 1

      # Transform counts to probabilities
      for w_tuple in model_ngram:
          total_count = float(sum(model_ngram[w_tuple].values()))
          for next_word in model_ngram[w_tuple]:
              model_ngram[w_tuple][next_word] /= total_count

      starting_seq_str = " ".join(starting_seq_tuple)
      next_word = dict(model_ngram[starting_seq_tuple])
      next_word_list = sorted(next_word, key=next_word.get, reverse=True)
      next_word_prob = [{i: round(next_word[i], 5)} for i in next_word_list]
      phrase_list_containing_starting_seq = [i for i in nufi_clean if starting_seq_str in i]

      with open(self.path_model_ngrams, 'wb') as file:
          pickle.dump(model_ngram, file)

      return next_word_list, next_word_prob, phrase_list_containing_starting_seq

  text = "ngɑ̌ mɑ́"
  text = "ngɑ̌ yú' mɑ́"
  text = "à kɑ̀'"

  n = len(text.split(" ")) + 1 # Set the desired value of n (n-gram order)
  def word_predict (self,text):

    next_word_list, next_word_prob, phrase_list_containing_starting_seq = self.model_generation_ngram(nufi_clean, nufi_tokens, text)

    print("next_word_list:\n", next_word_list)
    print()
    print("next_word_prob:\n", next_word_prob)
    print()
    print("Phrases Containing Starting Sequence:\n", phrase_list_containing_starting_seq)

  import random

  def text_generation_ngram(self,text="ngɑ̌ yú' mɑ́", model=model_ngram):

      n = self.ngrams_windows
      text = " ".join(text.lower().split())
      text = text.split(" ")
      text_ = text[:]

      if len(model[tuple(text_[-n+1:])].keys()) == 0:
          return f"{' '.join(text_)} not in corpus"

      sentence_finished = False

      while not sentence_finished:
          r = random.random()
          accumulator = .0
          tup = tuple(text_[-n+1:])
          for word in model[tuple(text_[-n+1:])].keys():
              accumulator += model[tuple(text_[-n+1:])][word]
              if accumulator >= r:
                  text_.append(word)
                  break

          if text_[-n+2:] == [None] * (n - 2):
              sentence_finished = True

      text_generated = ' '.join([t for t in text_ if t])

      if text_generated in nufi_clean:
          return ("Original", text_generated)
      else:
          return ("Text Generated", text_generated)

ngrams_windows = 4

path_model = os.path.join(base_dir, "data", "Nufi", f"Nufi_language_model_{ngrams_windows}gram.pickle")
NG = NufiTextGenerator(path_model,ngrams_windows)

initial_sq = "ngɑ̌ yú'"
initial_sq = "zēn zǒ"
initial_sq = "yāā sī"
initial_sq = "yì mfɑ̌’ lɑ́’ ntìè’"
initial_sq = "ǹ kɑ̀' ghʉ́"
# initial_sq = "pō kà kú'sí nàh nzáb"


# initial_sq = "ǒ sì"

next_word_list, next_word_prob, phrase_list_containing_starting_seq = \
NG.model_predictiction_ngram(nufi_clean, nufi_tokens, initial_text=initial_sq)

next_word_prob



"""# Load N-Gram Model"""

import pickle
from collections import defaultdict

# path_model = f"/content/drive/MyDrive/Data_Science/DataSets/Nufi/Nufi_language_model_{ngrams_windows}gram.pickle"

def create_defaultdict():
      return defaultdict(int)
  # Create a placeholder for model
model_ngram = defaultdict(create_defaultdict)

# Load the model from the pickle file
with open(path_model, 'rb') as file:
    model_ngram = pickle.load(file)

# model_ngram



initial_sq = "ngɑ̌ lén mɑ́"
text = initial_sq

n = len(text.split(" ")) + 1 # Set the desired value of n (n-gram order)

# text = "ǒ sì cáh wěn mbhì mɑ̄ njàm nnó'nɑ̄h"
# text = "ngɑ̌ lén"

sent_generated = []
c = 0
while True:

  c +=1

  if c==7900:
    break

  res = NG.text_generation_ngram(text=text, model=model_ngram)




  if res[0] == "Text Generated":
    sent_generated.append(res[1])

list(set(sent_generated))

# pip install gradio

import gradio as gr

# Assume NG.text_generation_ngram and model_ngram are predefined

def generate_text(input_text):
    # You can replace this with your actual text generation logic using the NG model
    res = NG.text_generation_ngram(text=input_text, model=model_ngram)

    return f"{res[0]}: {res[1]}"

NG.text_generation_ngram(text="ngɑ̌ yú'", model=model_ngram)

generate_text("ngɑ̌ yú'")

# # Set up Gradio interface
# iface = gr.Interface(fn=generate_text,
#                      inputs="text",
#                      outputs="text",
#                      live=True,  # Optional, makes it update live as the user types
#                      title="Text Generation with N-Grams",
#                      description="Enter a sequence of sentences, and the model will generate the next sentence.")

# # Launch the Gradio interface
# iface.launch()




force_dark_mode = """
function refresh() {
    const url = new URL(window.location);
    if (url.searchParams.get('__theme') !== 'dark') {
        url.searchParams.set('__theme', 'dark');
        window.location.href = url.href;
    }
}
"""
view = gr.Interface(
    fn=generate_text,
    inputs=[gr.Textbox(label="Your message:", lines=6)],
    outputs=[gr.Textbox(label="Response:", lines=6)],
    flagging_mode="never",
    js=force_dark_mode
)
view.launch(inbrowser=True)

import gradio as gr
import plotly.graph_objects as go
from plotly.subplots import make_subplots
import numpy as np

# Function to generate each plot
def sine_wave():
    x = np.linspace(0, 10, 100)
    y = np.sin(x)
    return go.Scatter(x=x, y=y, mode='lines', name="sin(x)")

def cosine_wave():
    x = np.linspace(0, 10, 100)
    y = np.cos(x)
    return go.Scatter(x=x, y=y, mode='lines', name="cos(x)")

def tangent_wave():
    x = np.linspace(-np.pi/2, np.pi/2, 100)
    y = np.tan(x)
    return go.Scatter(x=x, y=y, mode='lines', name="tan(x)")

def exponential_curve():
    x = np.linspace(0, 5, 100)
    y = np.exp(x)
    return go.Scatter(x=x, y=y, mode='lines', name="exp(x)")

def logarithmic_curve():
    x = np.linspace(0.1, 10, 100)  # Avoid log(0)
    y = np.log(x)
    return go.Scatter(x=x, y=y, mode='lines', name="log(x)")

# Main function to update the subplot based on user selection
def generate_subplots(selected_plots):
    fig = make_subplots(rows=2, cols=3,
                        subplot_titles=selected_plots,
                        specs=[[{"type": "scatter"}]*3, [{"type": "scatter"}]*3])

    plot_mapping = {
        "Sine Wave": sine_wave(),
        "Cosine Wave": cosine_wave(),
        "Tangent Wave": tangent_wave(),
        "Exponential Curve": exponential_curve(),
        "Logarithmic Curve": logarithmic_curve(),
    }

    row, col = 1, 1
    for plot in selected_plots:
        fig.add_trace(plot_mapping[plot], row=row, col=col)
        col += 1
        if col > 3:
            col = 1
            row += 1

    fig.update_layout(title_text="Interactive Multiple Plots", height=700, width=1000)
    return fig

# Define Gradio Interface
plot_options = ["Sine Wave", "Cosine Wave", "Tangent Wave", "Exponential Curve", "Logarithmic Curve"]

demo = gr.Interface(
    fn=generate_subplots,
    inputs=gr.CheckboxGroup(choices=plot_options, label="Select Plots to Display", value=plot_options[:3]),  # Default selects 3
    outputs=gr.Plot()
)

# Launch Gradio app
demo.launch()
